### ISSUE TITLE
Awesome buddy!

### ISSUE THREAD

**Issue by CandidKilsborne** [Roomack/Roomack.github.io#1]
Loving the responsive image backgrounds! I see you're using some opacity in there. One thing I notice, just out of pure chance of me having Dev Tools open is the links are jumping outside of the containers.
![screen shot 2014-06-15 at 5 32 47 pm](https://cloud.githubusercontent.com/assets/2257314/3282074/0184f32c-f4d5-11e3-9702-c409fdddcbe2.png)
I'm liking the hover color on the footer image links. I think it would be cool if you ran the header and footer background images through a blur effect, I think it might really make the content pop a bit. I have a script to do that so if you want I can. Oh and the links after visited are purple, I think either keeping the green or possibly using the blue for it. The pseudo element is :visited. I hope that I'm not coming across the wrong way with the changes. It's looking really good regardless.

**Comment by Roomack** [comment]
Hi Aaron,

Sorry I've been forgetting to check my hotmail account since I switched to gmail! 

You're not coming across poorly at all - thank you for the suggestions man.  I'll need to check my code as thought I had set :visited to stay green but apparently it's not working! And the blur effect you're talking about sounds awesome.  If appreciate it if you have an example I can take a look at. And so far as the links going outside the <div>s, do you mean when you try to resize the window?

Thanks for taking the time to give me feedback!

**Comment by CandidKilsborne** [comment]
No problem!
The links are the posts, like under cultural learnings, the link for week 2 is in between when you open dev tools. I think it might be because the divs have a fixed height, so when the dev tools screen opens, the divs may shrink but the links stay where they are. 
Here's a sample of the blur image.
![technology_landing-lb](https://cloud.githubusercontent.com/assets/2257314/3315927/a730c4ca-f6fd-11e3-8507-5319b7cfcddb.jpg)

**Comment by Roomack** [comment]
Ahhh gotcha! I'll check on my divs and set them to a percentage. And the blurred image is awesome!
